name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running basic test..."
          python -c "import fastapi; print('FastAPI imported successfully')"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-ml-app:latest .

      - name: Push Docker image
        run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-ml-app:latest
